spring:
    datasource:
        url: jdbc:mysql://localhost:3306/moj?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100


auth:
    jwt:
        secret: ${JWT_SECRET}
        accessExp: 86400000
        refreshExp: 86400000
        header: Authorization
        prefix: Bearer

bsm:
    client_id: ${BSM_CLIENT_ID}
    client_secret: ${BSM_CLIENT_SECRET}

neis:
    key: ${NEIS_KEY}
    mealUrl: ${NEIS_URL}
